apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: microbank-service-reader
kind: ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microbank-service-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
